### ISSUE TITLE
Ability to add custom variable extractors

### ISSUE THREAD

**Issue by juja0** [bpmn-io/extract-process-variables#15]
__Is your feature request related to a problem? Please describe__

The pre-defined extractors work well with known bpmn elements but for custom elements/plugins there's currently no way of extracting variables in a clean way.

__Describe the solution you'd like__

A way to register custom extractors.

__Describe alternatives you've considered__

Used patch-package to monkey patch the library to create and export a function like so

function registerVariableExtractor(extractor) {
  extractors.push(extractor);
}

__Additional context__

N/A

**Comment by marstamm** [comment]
Hi @juja0 ,

as this library is stateless, we could not add a `registerExtractor` function.

With https://github.com/bpmn-io/extract-process-variables/pull/23 it is now possible to pass an array of additional extractors as a second parameter. It is released as version v0.7.0
