### ISSUE TITLE
Get rid of unused _?_ peer dependency

### ISSUE THREAD

**Issue by nikku** [bpmn-io/extract-process-variables#17]
__What should we do?__

`camunda-bpmn-moddle` is unused as it looks like. Get rid of it as a peer dependency.

__Why should we do it?__

Don't depend on stuff that we do not need.

**Comment by pinussilvestrus** [comment]
Without `camunda-bpmn-moddle`, it would not be possible to retrieve the needed props, [as form fields](https://github.com/bpmn-io/extract-process-variables/blob/main/src/extractors/extractFormFields.js#L30). What we could argue is that it's not a peer dependency of this library, but of the bpmn-js-properties-panel implementation.

**Comment by nikku** [comment]
Yes, exactly. 

You'd need to verify against the run-time schema if the extension is loaded. Having it as a peer dependency does, unfortunately, nothing.
