### ISSUE TITLE
Increase extracting capabilities

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/extract-process-variables#3]
__What should we do?__

Currently, we only extract variables from `camunda:outputParameter` properties. We should investigate whether we can increase these, e.g. by `resultVariables` from script tasks.

* [x] Create a list of (reliable) process variable sources
* [x] Update extracting mechanism by those properties
  * [x] result variables (cf. [moddle descriptors](https://github.com/camunda/camunda-bpmn-moddle/blob/master/resources/camunda.json#L422))
  * [x] form field ids (cf. [moddle descriptors](https://github.com/camunda/camunda-bpmn-moddle/blob/master/resources/camunda.json#L972))
  * [x] call activity out mappings

__Why should we do it?__

More process variables suggestions to work with.

**Comment by volkergersabeck** [comment]
Additional sources are:

- Result Variable of Script Task or DMN Business Rule Tasks
- Form Field IDs (user tasks or start events)
- (maybe?) Out mapping of Call Activities
- OutputMappings of Intermediate Events

**Comment by pinussilvestrus** [comment]
> OutputMappings of Intermediate Events

this should already be included

![Kapture 2020-08-11 at 16 28 12](https://user-images.githubusercontent.com/9433996/89909724-ac251700-dbef-11ea-80bc-596c66fdad8a.gif)
